language: node_js
sudo: required
node_js:
  - "7"

install:
  - npm install

script:
  - npm test

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash deploy.sh
    on:
      branch: travis
